# Actividad
| Nombre  | Matrícula |
|---------|-----------|
| Josephine Esposito | A00827145 |
| Mauricio Maqueo Huerta | A01620649 |
| Guillermo Tafoya Milo| A01633790 |

# Entregar 
Archivo PDF de la actividad y la liga de la actividad en su repostitorio.

# Nota: 
Las tareas 1 a la 5 se califican como entregadas o no entregadas.

Al integrante que no participe en la actividad no se le tomará en cuenta para la calificación.

El límite para entregar las actividades es el viernes antes de las 23:59.

In [1]:
# Si trabajamos en Google Colaboratory corremos las siguientes lineas de código
from google.colab import drive
drive.mount('/gdrive')

ModuleNotFoundError: No module named 'google.colab'

In [ ]:
# Nos cambiamos a la carpeta donde tengamos el repositorio. Si es otra carpeta asegúrate de cambiar la ruta.
%cd /gdrive/MyDrive/SemanaTec/arte-analitica

# Insurance dataset

El dataset contiene información demográfica sobre los asegurado en una compañía de seguros:

- age: edad del asegurado principal
- sex: género del asegurado. female o male
- bmi: índice de masa corporal
- children: numero de niños que estan cubiertos con la poliza. 
- smoke: si fuma el beneficiario. yes/no
- region: dónde vive el beneficiario. Estos datos son de Estados Unidos. Regiones disponibles: northeast, southeast, southwest, northwest
- charges: costo del seguro.

# Actividad
Carga el dataset  **`data/insurance.csv`** y haz un análisis estadístico de las variables.

In [2]:
# Read the data
import pandas as pd
import numpy as np
path = "./data/"
df = pd.read_csv(path + "insurance.csv")

In [3]:
# Print the first 5 rows of the dataframe.
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [4]:
# Statistics of the numerical columns
df.describe()

               age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010

In [5]:
# ¿Cómo se correlacionan las variables numéricas entre sí?
df.corr()
# ¿Cuáles son las variables que tienen más correlación con los costos del seguro?
# De acuerdo a la correlacion, las variables age y charges

               age       bmi  children   charges
age       1.000000  0.109272  0.042469  0.299008
bmi       0.109272  1.000000  0.012759  0.198341
children  0.042469  0.012759  1.000000  0.067998
charges   0.299008  0.198341  0.067998  1.000000

In [10]:
# ¿Cuántas asegurados son hombres y cuántas son mujeres?
print("Hombre:",len(df[df["sex"]=="male"]))
print("Mujeres:",len(df[df["sex"]=="female"]))
print("Total:",len(df["sex"]))

Hombre: 676
Mujeres: 662
Total: 1338

In [11]:
# En promedio, ¿quién paga más de cuota de seguro, los fumadores o no fumadores? Muéstralo con los datos

# Get the difference of the averagre of the column charges bewteen smokers and non smokers
print("Diferencia de promedio de cuota de seguro entre fumadores y no fumadores:",df[df["smoker"]=="yes"]["charges"].mean()-df[df["smoker"]=="no"]["charges"].mean())

Diferencia de promedio de cuota de seguro entre fumadores y no fumadores: 23615.963533676637

In [14]:
# ¿Cuál es la región con más variabilidad en la cuota de seguro? Muéstralo con los datos

# Get the standard deviation of the column charges by region
print("Región con mayor desviación estandar:",df.groupby("region")["charges"].std().idxmax())

Región con mayor desviación estandar: southeast

# Guardar el resultado como pdf

[Liga al repositorio del equipo 4](https://github.com/ltchycrane/Semana_Tec)

* Exporta el notebook a formato HTML.

In [ ]:
! jupyter nbconvert --to HTML '/content/drive/MyDrive/SemanaTec/arte-analitica/4.2 - Actividad - Estadisticas de datos.ipynb'

* Haz doble clic en el archivo nuevo que se creó dentro de la carpeta `arte-analitica` y en la parte superior derecha dale clic en **imprimir**

* Imprime el archivo como *PDF* y súbelo a Canvas.